use swiggydb;

SELECT *FROM customers;
SELECT * FROM complaints;
SELECT * FROM deliverypartners;
SELECT * FROM deliveryupdates;
SELECT * FROM feedback;
SELECT * FROM menuitems;
SELECT * FROM orderitems;
SELECT * FROM orders;
SELECT * FROM payment;
SELECT * FROM restaurants;
Select * from orderdelivery;
-- Display all customers who live in 'Delhi'.
SELECT 
    *
FROM
    customers
WHERE
    city = 'Delhi';

-- Find the average rating of all restaurants in 'Mumbai'.
SELECT 
    *
FROM
    restaurants;
SELECT 
    ROUND(AVG(rating)) avg_rating
FROM
    restaurants
WHERE
    city = 'Mumbai';

-- List all customers who have placed at least one order.

SELECT 
    c.name, c.customer_id, COUNT(o.order_id) total_orders
FROM
    customers AS c
        INNER JOIN
    orders AS o ON c.customer_id = o.customer_id
GROUP BY c.customer_id
ORDER BY total_orders;

-- Find the total revenue generated by each restaurant.

SELECT 
    restaurant_id, SUM(total_amount) AS total_revenue
FROM
    orders
WHERE
    status = 'completed'
GROUP BY restaurant_id;

-- Find the top 5 restaurants with the highest average rating. 
SELECT 
    name, ROUND(AVG(rating), 2) AS avg_rating
FROM
    restaurants
WHERE
    rating IS NOT NULL
GROUP BY name
ORDER BY AVG(rating) DESC
LIMIT 5;

-- Display all customers who have never placed an order.

SELECT 
    c.customer_id, c.name, COUNT(o.order_id) total_orders
FROM
    customers AS c
        LEFT JOIN
    orders AS o ON c.customer_id = o.customer_id
GROUP BY c.customer_id
HAVING COUNT(o.order_id) = 0
ORDER BY total_orders;

	-- Find the number of orders placed by each customer in 'Mumbai'.
	SELECT 
    c.customer_id, c.name, COUNT(o.order_id) AS total_orders
FROM
    customers c
        LEFT JOIN
    orders o ON c.customer_id = o.customer_id
WHERE
    c.city = 'Mumbai'
GROUP BY c.customer_id , c.name
ORDER BY COUNT(o.order_id) DESC;


-- Display all orders placed in the last 30 days.
SELECT *
FROM Orders
WHERE order_date >= (
    SELECT DATE(MAX(order_date) - INTERVAL 30 DAY) FROM Orders
)
ORDER BY order_date DESC;

-- List all delivery partners who have completed more than 1 delivery
SELECT * FROM deliverypartners; 
Select * from orderdelivery;

select dp.partner_id,dp.name,count(od.order_delivery_id) as delivery_count
from deliverypartners as dp
left join 
orderdelivery as od
on dp.partner_id=od.partner_id
group by dp.partner_id,dp.name
having count(od.order_delivery_id)>1
order by count(od.order_delivery_id) desc;

-- Find the customers who have placed orders on exactly three different days.
SELECT * FROM orders;
SELECT *FROM customers;
SELECT 
    c.customer_id,
    c.name,
    COUNT(DISTINCT DATE(o.order_date)) AS unique_order_days
FROM Orders o
JOIN Customers c
    ON o.customer_id = c.customer_id
GROUP BY c.customer_id, c.name
HAVING COUNT(DISTINCT DATE(o.order_date)) = 3;

-- Find the delivery partner who has worked with the most different customers.
select * from orderdelivery;
select * from orders;
select * from deliverypartners;
select  dp.partner_id,dp.name,count(distinct o.customer_id) customer_count
from orderdelivery od 
join deliverypartners dp
on od.partner_id=dp.partner_id
join orders o 
on o.order_id=od.order_id
group by dp.partner_id,dp.name
order by count(distinct o.customer_id) desc ;

-- Identify customers who have the same city and have placed orders at the same restaurants, but on different dates.
select * from customers;
select * from restaurants;
select * from orders;
SELECT DISTINCT c1.customer_id customer_1, c1.name, c2.customer_id customer_2, c2.name, c1.city,r.name 
FROM orders o1
JOIN
orders o2 ON o1.restaurant_id = o2.restaurant_id
JOIN
customers c1 ON o1.customer_id = c1.customer_id
JOIN
customers c2 ON o2.customer_id = c2.customer_id
        JOIN
    restaurants r ON o1.restaurant_id = r.restaurant_id
WHERE
    c1.city = c2.city
        AND c1.customer_id < c2.customer_id
        AND DATE(o1.order_date) <> DATE(o2.order_date);

